<a href="https://colab.research.google.com/github/TimkaThymineTimiryazevskaya/sf_data_science/blob/main/Python_tink.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import numpy as np
import pandas as pd
import random

In [97]:
!pip3 install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (1.22.4)

In [122]:
col_1 = 0

In [126]:
N = 1000 
k_ = 1 
seed = "АДВИ_2023"
random.seed(seed)

col_1 = []
for i in range(1,1001):
  col_1.append(i)
random.shuffle(col_1)
print(col_1)
 
grp_lst = ["группа_1", "группа_2", "группа_3", "группа_4", "группа_5"] 
col_2 = [] 
for i in range(N): 
    col_2.append(random.choices(grp_lst, k=k_)[0]) 
print(col_2)   
 
col_3 = [] 
for i in range(N):  
    col_3.append(random.randint(50, 100))
print(col_3)

[476, 315, 490, 748, 471, 907, 457, 826, 5, 646, 477, 392, 309, 136, 655, 816, 794, 586, 984, 421, 137, 848, 722, 512, 934, 125, 959, 903, 976, 122, 422, 654, 805, 472, 272, 789, 42, 755, 858, 581, 781, 526, 74, 479, 432, 962, 919, 711, 637, 448, 769, 447, 463, 544, 564, 341, 257, 14, 704, 197, 235, 886, 232, 737, 427, 117, 163, 171, 900, 624, 672, 425, 638, 412, 213, 694, 121, 268, 347, 763, 790, 289, 107, 687, 983, 961, 219, 684, 768, 222, 966, 406, 730, 809, 888, 628, 338, 46, 563, 626, 691, 26, 515, 632, 896, 274, 102, 444, 872, 352, 788, 381, 625, 665, 599, 994, 899, 201, 692, 450, 664, 297, 12, 989, 149, 150, 863, 808, 569, 571, 139, 294, 114, 867, 978, 708, 339, 418, 778, 521, 980, 754, 420, 633, 829, 353, 712, 607, 548, 109, 302, 73, 960, 572, 566, 243, 635, 317, 774, 986, 446, 588, 123, 192, 702, 618, 723, 503, 405, 190, 717, 462, 562, 58, 725, 885, 155, 550, 65, 157, 577, 480, 525, 873, 894, 688, 683, 992, 850, 822, 913, 140, 690, 326, 377, 557, 413, 25, 283, 944, 173, 108, 419, 938, 887, 977, 225, 720, 842, 932, 578, 552, 436, 594, 500, 580, 556, 838, 104, 534, 465, 320, 565, 8, 874, 359, 147, 757, 570, 391, 855, 998, 90, 80, 298, 909, 582, 813, 875, 883, 990, 746, 89, 135, 880, 415, 670, 200, 832, 881, 31, 747, 627, 401, 948, 253, 267, 17, 35, 853, 32, 433, 271, 263, 128, 600, 204, 469, 709, 234, 194, 796, 543, 505, 248, 653, 207, 129, 376, 657, 910, 273, 601, 301, 492, 906, 426, 623, 797, 468, 524, 925, 261, 258, 753, 767, 368, 343, 409, 86, 963, 99, 57, 159, 727, 766, 209, 701, 407, 411, 991, 239, 847, 710, 255, 529, 454, 929, 592, 169, 892, 33, 975, 152, 533, 859, 954, 464, 369, 30, 841, 393, 749, 652, 388, 470, 820, 335, 491, 602, 153, 777, 174, 459, 374, 474, 49, 598, 682, 828, 332, 191, 124, 617, 922, 355, 531, 455, 613, 987, 318, 20, 952, 371, 68, 64, 643, 752, 442, 926, 560, 532, 305, 277, 511, 385, 348, 78, 246, 620, 645, 651, 440, 751, 734, 75, 537, 484, 882, 397, 189, 501, 131, 996, 29, 333, 71, 103, 744, 846, 417, 890, 798, 55, 715, 999, 178, 971, 82, 589, 514, 181, 639, 542, 118, 475, 898, 229, 79, 56, 345, 539, 538, 783, 156, 726, 817, 262, 965, 59, 871, 837, 818, 210, 719, 771, 988, 891, 958, 834, 175, 199, 110, 15, 831, 7, 179, 97, 456, 782, 982, 696, 583, 69, 98, 680, 349, 902, 390, 668, 245, 287, 120, 681, 180, 595, 508, 370, 379, 92, 396, 513, 488, 555, 636, 658, 41, 946, 536, 13, 495, 66, 621, 535, 950, 467, 942, 949, 644, 221, 300, 731, 584, 901, 596, 96, 558, 974, 918, 182, 861, 915, 793, 759, 266, 969, 591, 650, 593, 486, 561, 158, 9, 358, 761, 860, 785, 461, 313, 630, 138, 866, 585, 143, 724, 249, 845, 310, 606, 498, 186, 864, 408, 67, 386, 327, 807, 912, 510, 518, 939, 264, 931, 322, 540, 228, 113, 674, 775, 27, 160, 70, 516, 622, 868, 230, 801, 269, 981, 779, 502, 935, 3, 733, 168, 184, 608, 642, 856, 649, 865, 220, 141, 568, 187, 375, 256, 953, 87, 616, 758, 460, 836, 295, 590, 226, 2, 517, 481, 786, 185, 389, 605, 303, 964, 434, 937, 414, 337, 276, 354, 703, 574, 799, 648, 473, 678, 279, 451, 28, 242, 346, 366, 527, 641, 489, 686, 356, 387, 661, 214, 357, 493, 541, 111, 945, 718, 528, 700, 792, 803, 85, 88, 973, 478, 403, 995, 985, 693, 115, 656, 765, 851, 914, 957, 133, 288, 923, 523, 307, 154, 854, 827, 669, 95, 615, 384, 101, 328, 609, 429, 60, 968, 640, 800, 770, 11, 431, 947, 677, 254, 195, 824, 188, 604, 119, 285, 756, 373, 325, 441, 614, 350, 522, 398, 208, 458, 739, 93, 825, 666, 292, 53, 575, 740, 83, 382, 897, 576, 634, 314, 439, 91, 553, 546, 787, 84, 94, 365, 244, 699, 127, 45, 38, 21, 876, 804, 404, 997, 839, 231, 112, 452, 812, 706, 372, 736, 499, 227, 819, 554, 833, 941, 713, 48, 394, 23, 567, 311, 843, 270, 840, 689, 193, 367, 870, 631, 81, 202, 979, 917, 324, 216, 351, 44, 970, 323, 151, 494, 164, 236, 167, 424, 321, 445, 697, 170, 126, 573, 889, 660, 196, 342, 852, 893, 530, 16, 233, 430, 206, 19, 857, 134, 304, 105, 849, 395, 410, 878, 291, 884, 921, 331, 362, 211, 519, 52, 265, 423, 344, 10, 879, 685, 732, 773, 336, 675, 673, 504, 437, 764, 721, 955, 695, 496, 507, 1, 50, 296, 745, 299, 679, 776, 811, 316, 47, 72, 223, 237, 612, 551, 810, 43, 116, 238, 176, 399, 795, 308, 198, 735, 217, 240, 361, 39, 380, 877, 667, 830, 487, 51, 662, 603, 802, 520, 506, 215, 806, 835, 951, 330, 933, 453, 247, 943, 482, 319, 280, 928, 54, 1000, 549, 40, 967, 251, 659, 402, 443, 416, 383, 676, 815, 911, 172, 784, 821, 780, 334, 629, 34, 449, 378, 559, 435, 76, 132, 275, 400, 37, 61, 162, 545, 698, 760, 714, 36, 862, 252, 165, 579, 823, 428, 284, 762, 259, 707, 728, 250, 904, 743, 663, 483, 716, 100, 547, 177, 814, 290, 77, 22, 705, 742, 619, 142, 485, 791, 772, 363, 224, 920, 130, 293, 145, 166, 278, 671, 340, 610, 364, 924, 62, 282, 241, 729, 908, 438, 895, 144, 750, 905, 916, 497, 148, 203, 183, 844, 869, 993, 106, 930, 312, 611, 218, 936, 940, 509, 212, 466, 281, 329, 4, 18, 647, 63, 306, 6, 956, 597, 286, 24, 741, 360, 927, 205, 738, 260, 146, 972, 161, 587]
['группа_1', 'группа_5', 'группа_4', 'группа_3', 'группа_5', 'группа_2', 'группа_2', 'группа_1', 'группа_3', 'группа_3', 'группа_5', 'группа_4', 'группа_4', 'группа_4', 'группа_2', 'группа_4', 'группа_4', 'группа_5', 'группа_1', 'группа_5', 'группа_4', 'группа_1', 'группа_2', 'группа_2', 'группа_4', 'группа_2', 'группа_3', 'группа_2', 'группа_2', 'группа_3', 'группа_2', 'группа_1', 'группа_2', 'группа_3', 'группа_3', 'группа_3', 'группа_1', 'группа_4', 'группа_3', 'группа_1', 'группа_3', 'группа_5', 'группа_4', 'группа_2', 'группа_2', 'группа_1', 'группа_5', 'группа_3', 'группа_4', 'группа_3', 'группа_4', 'группа_3', 'группа_1', 'группа_4', 'группа_1', 'группа_2', 'группа_1', 'группа_1', 'группа_2', 'группа_2', 'группа_3', 'группа_3', 'группа_4', 'группа_5', 'группа_3', 'группа_4', 'группа_2', 'группа_4', 'группа_1', 'группа_4', 'группа_1', 'группа_5', 'группа_4', 'группа_2', 'группа_4', 'группа_5', 'группа_2', 'группа_2', 'группа_2', 'группа_5', 'группа_3', 'группа_3', 'группа_4', 'группа_4', 'группа_3', 'группа_3', 'группа_1', 'группа_2', 'группа_5', 'группа_3', 'группа_2', 'группа_3', 'группа_2', 'группа_1', 'группа_2', 'группа_3', 'группа_5', 'группа_5', 'группа_1', 'группа_1', 'группа_4', 'группа_3', 'группа_4', 'группа_1', 'группа_3', 'группа_3', 'группа_3', 'группа_5', 'группа_5', 'группа_2', 'группа_5', 'группа_2', 'группа_2', 'группа_3', 'группа_4', 'группа_2', 'группа_1', 'группа_4', 'группа_1', 'группа_1', 'группа_1', 'группа_1', 'группа_3', 'группа_5', 'группа_5', 'группа_4', 'группа_5', 'группа_4', 'группа_4', 'группа_5', 'группа_5', 'группа_1', 'группа_3', 'группа_2', 'группа_5', 'группа_3', 'группа_2', 'группа_5', 'группа_4', 'группа_5', 'группа_3', 'группа_4', 'группа_4', 'группа_1', 'группа_3', 'группа_2', 'группа_1', 'группа_5', 'группа_4', 'группа_1', 'группа_5', 'группа_4', 'группа_5', 'группа_5', 'группа_5', 'группа_4', 'группа_4', 'группа_2', 'группа_1', 'группа_2', 'группа_4', 'группа_4', 'группа_3', 'группа_2', 'группа_1', 'группа_1', 'группа_1', 'группа_3', 'группа_1', 'группа_4', 'группа_5', 'группа_1', 'группа_2', 'группа_2', 'группа_3', 'группа_4', 'группа_3', 'группа_4', 'группа_1', 'группа_5', 'группа_1', 'группа_3', 'группа_2', 'группа_4', 'группа_5', 'группа_1', 'группа_5', 'группа_3', 'группа_4', 'группа_5', 'группа_4', 'группа_4', 'группа_3', 'группа_3', 'группа_1', 'группа_4', 'группа_4', 'группа_2', 'группа_1', 'группа_1', 'группа_2', 'группа_3', 'группа_1', 'группа_4', 'группа_1', 'группа_4', 'группа_3', 'группа_1', 'группа_4', 'группа_5', 'группа_3', 'группа_1', 'группа_2', 'группа_4', 'группа_5', 'группа_3', 'группа_5', 'группа_4', 'группа_4', 'группа_1', 'группа_4', 'группа_1', 'группа_5', 'группа_3', 'группа_3', 'группа_1', 'группа_5', 'группа_1', 'группа_5', 'группа_5', 'группа_3', 'группа_4', 'группа_2', 'группа_5', 'группа_3', 'группа_3', 'группа_1', 'группа_4', 'группа_4', 'группа_2', 'группа_2', 'группа_1', 'группа_3', 'группа_1', 'группа_4', 'группа_5', 'группа_1', 'группа_3', 'группа_5', 'группа_3', 'группа_4', 'группа_3', 'группа_4', 'группа_5', 'группа_1', 'группа_4', 'группа_1', 'группа_1', 'группа_4', 'группа_2', 'группа_4', 'группа_2', 'группа_5', 'группа_5', 'группа_2', 'группа_2', 'группа_2', 'группа_4', 'группа_2', 'группа_5', 'группа_1', 'группа_3', 'группа_1', 'группа_4', 'группа_1', 'группа_4', 'группа_1', 'группа_5', 'группа_2', 'группа_2', 'группа_4', 'группа_5', 'группа_2', 'группа_2', 'группа_1', 'группа_2', 'группа_4', 'группа_2', 'группа_2', 'группа_3', 'группа_4', 'группа_3', 'группа_1', 'группа_4', 'группа_4', 'группа_1', 'группа_3', 'группа_4', 'группа_5', 'группа_2', 'группа_1', 'группа_5', 'группа_2', 'группа_4', 'группа_2', 'группа_5', 'группа_1', 'группа_5', 'группа_1', 'группа_2', 'группа_3', 'группа_3', 'группа_4', 'группа_3', 'группа_1', 'группа_5', 'группа_5', 'группа_3', 'группа_5', 'группа_4', 'группа_1', 'группа_2', 'группа_3', 'группа_5', 'группа_2', 'группа_5', 'группа_5', 'группа_5', 'группа_2', 'группа_3', 'группа_1', 'группа_5', 'группа_5', 'группа_1', 'группа_5', 'группа_2', 'группа_5', 'группа_4', 'группа_1', 'группа_1', 'группа_5', 'группа_4', 'группа_5', 'группа_1', 'группа_2', 'группа_5', 'группа_1', 'группа_2', 'группа_5', 'группа_1', 'группа_3', 'группа_3', 'группа_4', 'группа_1', 'группа_4', 'группа_3', 'группа_4', 'группа_4', 'группа_1', 'группа_1', 'группа_2', 'группа_1', 'группа_3', 'группа_2', 'группа_3', 'группа_1', 'группа_5', 'группа_1', 'группа_1', 'группа_3', 'группа_1', 'группа_1', 'группа_1', 'группа_4', 'группа_4', 'группа_1', 'группа_3', 'группа_1', 'группа_5', 'группа_3', 'группа_5', 'группа_4', 'группа_3', 'группа_1', 'группа_3', 'группа_3', 'группа_1', 'группа_3', 'группа_3', 'группа_1', 'группа_3', 'группа_1', 'группа_2', 'группа_4', 'группа_4', 'группа_4', 'группа_2', 'группа_2', 'группа_2', 'группа_2', 'группа_1', 'группа_1', 'группа_2', 'группа_1', 'группа_2', 'группа_3', 'группа_1', 'группа_5', 'группа_3', 'группа_5', 'группа_5', 'группа_2', 'группа_1', 'группа_4', 'группа_3', 'группа_4', 'группа_1', 'группа_1', 'группа_4', 'группа_3', 'группа_3', 'группа_2', 'группа_3', 'группа_2', 'группа_4', 'группа_1', 'группа_4', 'группа_5', 'группа_1', 'группа_5', 'группа_3', 'группа_2', 'группа_3', 'группа_1', 'группа_4', 'группа_1', 'группа_2', 'группа_3', 'группа_1', 'группа_4', 'группа_5', 'группа_4', 'группа_2', 'группа_4', 'группа_5', 'группа_5', 'группа_3', 'группа_1', 'группа_4', 'группа_2', 'группа_2', 'группа_5', 'группа_2', 'группа_4', 'группа_5', 'группа_2', 'группа_2', 'группа_3', 'группа_4', 'группа_1', 'группа_5', 'группа_3', 'группа_4', 'группа_4', 'группа_3', 'группа_4', 'группа_3', 'группа_1', 'группа_2', 'группа_2', 'группа_4', 'группа_2', 'группа_1', 'группа_2', 'группа_5', 'группа_4', 'группа_2', 'группа_2', 'группа_1', 'группа_2', 'группа_5', 'группа_2', 'группа_2', 'группа_5', 'группа_3', 'группа_5', 'группа_5', 'группа_5', 'группа_5', 'группа_3', 'группа_2', 'группа_1', 'группа_1', 'группа_2', 'группа_4', 'группа_1', 'группа_2', 'группа_4', 'группа_3', 'группа_2', 'группа_2', 'группа_4', 'группа_5', 'группа_4', 'группа_3', 'группа_5', 'группа_2', 'группа_1', 'группа_3', 'группа_2', 'группа_1', 'группа_2', 'группа_4', 'группа_3', 'группа_4', 'группа_4', 'группа_4', 'группа_3', 'группа_3', 'группа_4', 'группа_2', 'группа_5', 'группа_1', 'группа_5', 'группа_4', 'группа_3', 'группа_4', 'группа_1', 'группа_5', 'группа_3', 'группа_2', 'группа_2', 'группа_4', 'группа_3', 'группа_4', 'группа_4', 'группа_4', 'группа_1', 'группа_5', 'группа_4', 'группа_3', 'группа_3', 'группа_1', 'группа_4', 'группа_3', 'группа_1', 'группа_2', 'группа_3', 'группа_1', 'группа_1', 'группа_5', 'группа_4', 'группа_4', 'группа_4', 'группа_2', 'группа_4', 'группа_4', 'группа_2', 'группа_2', 'группа_2', 'группа_1', 'группа_1', 'группа_2', 'группа_4', 'группа_3', 'группа_4', 'группа_4', 'группа_5', 'группа_1', 'группа_1', 'группа_4', 'группа_1', 'группа_2', 'группа_3', 'группа_1', 'группа_4', 'группа_5', 'группа_1', 'группа_5', 'группа_2', 'группа_2', 'группа_4', 'группа_3', 'группа_2', 'группа_4', 'группа_1', 'группа_1', 'группа_3', 'группа_2', 'группа_5', 'группа_4', 'группа_2', 'группа_4', 'группа_3', 'группа_4', 'группа_4', 'группа_5', 'группа_3', 'группа_2', 'группа_3', 'группа_4', 'группа_3', 'группа_1', 'группа_1', 'группа_2', 'группа_1', 'группа_2', 'группа_4', 'группа_4', 'группа_5', 'группа_4', 'группа_4', 'группа_3', 'группа_5', 'группа_1', 'группа_4', 'группа_2', 'группа_4', 'группа_3', 'группа_2', 'группа_3', 'группа_1', 'группа_2', 'группа_4', 'группа_4', 'группа_4', 'группа_1', 'группа_1', 'группа_3', 'группа_5', 'группа_2', 'группа_1', 'группа_5', 'группа_2', 'группа_1', 'группа_4', 'группа_2', 'группа_4', 'группа_5', 'группа_2', 'группа_4', 'группа_5', 'группа_1', 'группа_1', 'группа_2', 'группа_1', 'группа_1', 'группа_4', 'группа_2', 'группа_3', 'группа_3', 'группа_5', 'группа_3', 'группа_1', 'группа_5', 'группа_1', 'группа_1', 'группа_1', 'группа_4', 'группа_5', 'группа_3', 'группа_5', 'группа_1', 'группа_5', 'группа_2', 'группа_3', 'группа_3', 'группа_1', 'группа_1', 'группа_3', 'группа_3', 'группа_4', 'группа_4', 'группа_2', 'группа_2', 'группа_2', 'группа_3', 'группа_1', 'группа_1', 'группа_5', 'группа_2', 'группа_4', 'группа_2', 'группа_5', 'группа_3', 'группа_5', 'группа_3', 'группа_2', 'группа_2', 'группа_2', 'группа_1', 'группа_2', 'группа_2', 'группа_2', 'группа_4', 'группа_2', 'группа_2', 'группа_1', 'группа_2', 'группа_4', 'группа_3', 'группа_4', 'группа_2', 'группа_1', 'группа_4', 'группа_5', 'группа_4', 'группа_4', 'группа_2', 'группа_5', 'группа_5', 'группа_5', 'группа_1', 'группа_5', 'группа_5', 'группа_1', 'группа_4', 'группа_5', 'группа_5', 'группа_3', 'группа_3', 'группа_3', 'группа_3', 'группа_4', 'группа_1', 'группа_1', 'группа_3', 'группа_5', 'группа_2', 'группа_2', 'группа_2', 'группа_5', 'группа_3', 'группа_3', 'группа_4', 'группа_1', 'группа_4', 'группа_3', 'группа_2', 'группа_2', 'группа_5', 'группа_4', 'группа_5', 'группа_4', 'группа_4', 'группа_5', 'группа_2', 'группа_4', 'группа_2', 'группа_2', 'группа_1', 'группа_3', 'группа_1', 'группа_4', 'группа_5', 'группа_5', 'группа_2', 'группа_1', 'группа_4', 'группа_2', 'группа_5', 'группа_4', 'группа_3', 'группа_5', 'группа_5', 'группа_4', 'группа_4', 'группа_3', 'группа_2', 'группа_5', 'группа_1', 'группа_3', 'группа_3', 'группа_3', 'группа_3', 'группа_4', 'группа_4', 'группа_4', 'группа_4', 'группа_5', 'группа_1', 'группа_4', 'группа_5', 'группа_3', 'группа_2', 'группа_1', 'группа_5', 'группа_1', 'группа_3', 'группа_1', 'группа_3', 'группа_2', 'группа_5', 'группа_2', 'группа_5', 'группа_4', 'группа_5', 'группа_5', 'группа_4', 'группа_5', 'группа_4', 'группа_2', 'группа_2', 'группа_1', 'группа_4', 'группа_4', 'группа_5', 'группа_1', 'группа_5', 'группа_1', 'группа_5', 'группа_1', 'группа_3', 'группа_5', 'группа_2', 'группа_1', 'группа_3', 'группа_2', 'группа_3', 'группа_1', 'группа_1', 'группа_3', 'группа_3', 'группа_5', 'группа_4', 'группа_4', 'группа_4', 'группа_2', 'группа_4', 'группа_3', 'группа_1', 'группа_4', 'группа_3', 'группа_2', 'группа_5', 'группа_5', 'группа_3', 'группа_1', 'группа_4', 'группа_3', 'группа_3', 'группа_1', 'группа_2', 'группа_3', 'группа_4', 'группа_2', 'группа_2', 'группа_2', 'группа_3', 'группа_4', 'группа_4', 'группа_5', 'группа_4', 'группа_4', 'группа_1', 'группа_1', 'группа_5', 'группа_1', 'группа_4', 'группа_1', 'группа_2', 'группа_5', 'группа_3', 'группа_4', 'группа_3', 'группа_5', 'группа_4', 'группа_4', 'группа_5', 'группа_1', 'группа_5', 'группа_5', 'группа_4', 'группа_1', 'группа_2', 'группа_5', 'группа_5', 'группа_2', 'группа_1', 'группа_5', 'группа_2', 'группа_1', 'группа_1', 'группа_4', 'группа_5', 'группа_3', 'группа_1', 'группа_3', 'группа_2', 'группа_2', 'группа_5', 'группа_1', 'группа_1', 'группа_5', 'группа_3', 'группа_5', 'группа_4', 'группа_1', 'группа_2', 'группа_2', 'группа_4', 'группа_2', 'группа_5', 'группа_3', 'группа_3', 'группа_3', 'группа_2', 'группа_2', 'группа_1', 'группа_3', 'группа_5', 'группа_1', 'группа_2', 'группа_3', 'группа_1', 'группа_1', 'группа_1', 'группа_3', 'группа_4', 'группа_3', 'группа_5', 'группа_3', 'группа_4', 'группа_1', 'группа_5', 'группа_3', 'группа_1', 'группа_3', 'группа_3', 'группа_5', 'группа_1', 'группа_4', 'группа_4', 'группа_2', 'группа_1', 'группа_4', 'группа_1', 'группа_5', 'группа_1', 'группа_4', 'группа_4', 'группа_4', 'группа_1', 'группа_1', 'группа_1', 'группа_1', 'группа_3', 'группа_2', 'группа_3', 'группа_4', 'группа_3', 'группа_2', 'группа_2', 'группа_4', 'группа_4', 'группа_1', 'группа_4', 'группа_2', 'группа_5', 'группа_2', 'группа_2', 'группа_4', 'группа_5', 'группа_1', 'группа_4', 'группа_1', 'группа_3', 'группа_1', 'группа_4', 'группа_3', 'группа_4', 'группа_1', 'группа_2', 'группа_1', 'группа_3', 'группа_4', 'группа_1', 'группа_4', 'группа_5', 'группа_1', 'группа_4', 'группа_5', 'группа_3', 'группа_2', 'группа_2', 'группа_5', 'группа_1', 'группа_3', 'группа_1', 'группа_1', 'группа_4', 'группа_2', 'группа_4', 'группа_5', 'группа_2', 'группа_4', 'группа_4', 'группа_1', 'группа_1', 'группа_5']

In [127]:
col_4, col_5, col_6 = [], [], [] 
mu1, mu2, mu3 = 0, 0, 50 
sigma1, sigma2, sigma3 = 1, 12, 9 
for i in range(1, N+1): 
    col_4.append(random.gauss(mu1, sigma1)) 
for i in range(1, N+1): 
    col_5.append(random.gauss(mu2, sigma2)) 
for i in range(1, N+1): 
    col_6.append(random.gauss(mu3, sigma3)) 
 
col_4[0], col_5[0], col_6[0]

(3.01029133931237, 2.156346051014784, 57.45585127992099)

In [137]:
data = pd.DataFrame({'index':col_1, 'groups':col_2, 'uniform':col_3, 'gauss_1':col_4, 'gauss_2':col_5, 'gauss_3':col_6})
data

     index    groups  uniform   gauss_1    gauss_2    gauss_3
0      476  группа_1       95  3.010291   2.156346  57.455851
1      315  группа_5       77  0.190277  -9.934550  62.694177
2      490  группа_4       96 -0.282161   9.211071  54.688895
3      748  группа_3       56  1.127080 -12.391793  30.192353
4      471  группа_5       52 -1.238270  10.938748  52.682052
..     ...       ...      ...       ...        ...        ...
995    260  группа_4       57 -1.484164  -5.911598  49.330196
996    146  группа_4       78 -0.379041  -3.132954  60.329900
997    972  группа_1       52 -0.857206   0.835715  51.926114
998    161  группа_1       62 -0.195475   3.496498  66.310250
999    587  группа_5       60  0.093496  -9.164475  60.897843

[1000 rows x 6 columns]

In [142]:
data.index = col_1
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 476 to 587
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    1000 non-null   int64
 1   groups   1000 non-null   object
 2   uniform  1000 non-null   int64
 3   gauss_1  1000 non-null   float64
 4   gauss_2  1000 non-null   float64
 5   gauss_3  1000 non-null   float64
dtypes: float64(3), int64(2), object(1)
memory usage: 54.7+ KB

In [143]:
df = data.copy()

In [144]:
df.loc[df.index %121==0, 'gauss_1'] = None
df.loc[np.modf(df.gauss_2)[0]>0.95, 'gauss_2'] = None
df['gauss_2'].fillna(df.gauss_2.mean(), inplace = True)
df.dropna(subset = 'gauss_1', inplace = True)

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 992 entries, 476 to 587
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    992 non-null    int64
 1   groups   992 non-null    object
 2   uniform  992 non-null    int64
 3   gauss_1  992 non-null    float64
 4   gauss_2  992 non-null    float64
 5   gauss_3  992 non-null    float64
dtypes: float64(3), int64(2), object(1)
memory usage: 54.2+ KB

In [147]:
print(df['gauss_2'].mean(), df['gauss_2'].std() )

-0.4737990825631301 12.069963943907617

In [156]:
print(df['groups'].mode()[0])

группа_4

In [158]:
a = df['groups'].mode()
print(df['groups'].mode())
print(df[df['groups'] == a[0]].count())

0    группа_4
Name: groups, dtype: object
index      222
groups     222
uniform    222
gauss_1    222
gauss_2    222
gauss_3    222
dtype: int64

In [167]:
df[df['groups'] == 'группа_5'].head(1)

     index    groups  uniform   gauss_1  gauss_2    gauss_3
315    315  группа_5       77  0.190277 -9.93455  62.694177

In [168]:
df[df['uniform'] >= np.percentile(df.uniform, 90)].count()

index      118
groups     118
uniform    118
gauss_1    118
gauss_2    118
gauss_3    118
dtype: int64

In [184]:
df.groupby('groups').median()

          index  uniform   gauss_1   gauss_2    gauss_3
groups
группа_1  551.0     77.0  0.060626 -0.627803  49.876708
группа_2  463.5     75.5 -0.057600 -0.473472  49.990529
группа_3  464.5     77.0  0.055329 -0.369613  49.459261
группа_4  492.0     74.0 -0.079226 -0.434114  49.069511
группа_5  510.0     74.0  0.065264 -1.145277  49.936910

In [187]:
df.groupby('groups').min()

          index  uniform   gauss_1    gauss_2    gauss_3     gauss
groups
группа_1      2       50 -3.628448 -22.109394  21.111701 -0.770711
группа_2      3       50 -2.692705 -38.365537  26.063885 -0.843414
группа_3      1       50 -2.606773 -36.187520  27.741795 -0.784322
группа_4      4       50 -3.933254 -29.901064  19.682732 -0.841952
группа_5      6       50 -2.639733 -40.394911  29.945906 -1.029372

In [186]:
df['gauss'] = (df['gauss_1']+df['gauss_2'])/df['gauss_3']
np.percentile(df.gauss, 70)

0.10641825158661447